### ISSUE TITLE
Issue with DONT_NEGATE_STRIDES

### ISSUE THREAD

**Issue by theopavlakou** [fonnesbeck/ScipySuperpack#53]
Hey I am trying to run some of my code but I end up with a problem and the log shows this:

"The error is: RuntimeError: Iterator CreateCompatibleStrides may only be called if DONT_NEGATE_STRIDES was used to prevent reverse iteration of an axis"

I also have opened a stackexchange question on this and have been told that it would be good to tell you about it. The link is:

http://stackoverflow.com/questions/24164343/python-runtimeerror-iterator-createcompatiblestrides-may-only-be-called-if-don/24181193#24181193

Could this be fixed?

Thanks, 
Theo

**Comment by fonnesbeck** [comment]
Closing. Reopen if this is still an issue.
