### ISSUE TITLE
Error [Errno 13] Permission denied "My_Home_Folder/.matplotlib/fontList.cache" after updating

### ISSUE THREAD

**Issue by Vital-Fernandez** [fonnesbeck/ScipySuperpack#56]
Hi, I wonder if you could help me with this issue:

I have been given an old mac laptop with which I am not really familiar. I had the matplotlib version 1.1.1 and I wanted to update to 1.4 since I had some issues with matplotlib.

Actually, I had the same issue as in this post : (http://stackoverflow.com/questions/21473600/matplotlib-version). This is were I found the link to your script.

Now when I run "matplotlib.**version**" I get u'1.4.x' that's good.

However, when I try to import pylab I get this error:

 [Errno 13] Permission denied "My_Home_Folder/.matplotlib/fontList.cache" 

Please any advice on how to solve this would be very helpfull

UPDATE: That solution worked, thank you!!

**Comment by RobertGru** [comment]
Deleting the cache file solved the problem for me.  Thank you.

**Comment by ahmetanildindar** [comment]
Same problem and same solution. Thank you mates.
