### ISSUE TITLE
clone size

### ISSUE THREAD

**Issue by epifanio** [fonnesbeck/ScipySuperpack#62]
the total size of the clone is ```1.41 GB``` 
most of the files are in : 
ScipySuperpack/.git/objects/pack

```
git clone https://github.com/fonnesbeck/ScipySuperpack
Cloning into 'ScipySuperpack'...
remote: Counting objects: 1035, done.
remote: Total 1035 (delta 0), reused 0 (delta 0), pack-reused 1035
Receiving objects: 100% (1035/1035), 1.31 GiB | 3.43 MiB/s, done.
Resolving deltas: 100% (470/470), done.
Checking connectivity... done.
```

perhaps it should be removed  from the repo ?

**Comment by fonnesbeck** [comment]
I need to truncate the history of the repo, since I used to distribute binaries of the packages. Thanks for calling it to my attention.

**Comment by fonnesbeck** [comment]
I've removed all the .egg files from the history. It is much smaller now.
