### ISSUE TITLE
Why use openblas?

### ISSUE THREAD

**Issue by tdsmith** [fonnesbeck/ScipySuperpack#64]
Apple's Accelerate framework is performant and already present.

**Comment by fonnesbeck** [comment]
I had heard there were issues related to the `multiprocessing` module when building against Accelerate, but that may be outdated information. Does Accelerate provide better performance for NumPy than OpenBLAS? I hadn't seen any benchmarks.

I suppose I could ask the user what they want to use.

**Comment by fonnesbeck** [comment]
I've added an option in the [accelerate branch](/fonnesbeck/ScipySuperpack/tree/accelerate) if you'd like to try it. Will still default to OpenBLAS, but will ask if you'd like not to.

**Comment by tdsmith** [comment]
In some informal benchmarks I've seen, openblas is at least not faster: https://github.com/xianyi/OpenBLAS/issues/533

**Comment by fonnesbeck** [comment]
OK, switched to Accelerate in master.
